version: 2.1
jobs:
  # デプロイ用のジョブ
  deploy:
    # docker compose　を利用するため、仮想マシンを利用する。（最新版のimageは下記URLを参照）
    # See: https://circleci.com/docs/ja/configuration-reference#available-linux-machine-images
    machine:
      image: ubuntu-2204:current
    # 作業用のディレクトリを設定（ディレクトリ名はVercelのプロジェクト名と合わせる）
    working_directory: ~/spa
    # タスクを定義
    steps:
      # リポジトリを作業用のディレクトリにpull
      - checkout
      # 処理を実行
      # yarnをインストール
      - run:
          name: yarn.lockからyarnを再インストール
          command: docker compose run --rm front yarn install --frozen-lockfile
      # vercelへのデプロイ処理
      - run:
          name: yarn deploy
          command: yarn deploy

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-and-deploy-wf:
    jobs:
      - deploy:
          filters:
            branches:
              only: main